### ISSUE TITLE
Discussion: Extension Branding

### ISSUE THREAD

**Issue by SebastianSchuetze** [pnp/sp-alm-devops-extension#2]
In the pull request #1 it came up that we should align on the branding of the extension.

There are two manifest files that we need to agree on:
- vss-extemsopn.sjon manifest
- task.json manifest of the pipeline task.

I will write down the current information that is in the manifests and is up to us to decide.

#### vss-extension.json
```
{
    "id": "pnp-sp-alm-devops-extension",
    "name": "O365 And PnP Pipelines Tasks",
    "publisher": "SharePoint PnP",
    "description": "Tasks for Builds and Releases empowered by the PnP Community.",
    "tags": [
        "SharePoint", "PnP","SharePoint Online","SharePoint 2016","SharePoint 2013",
        "xml", "deployment","O365",
        "PowerShell","Provisioning", "Provisioning Engine"
    ],
    "icons": {
        "default": "Images/Icon128.png",
        "large": "Images/Icon512.png"
    },
    "content": {
        "details": {
            "path": "overview.md"
        }
    },
    "branding": {
        "color": "rgb(240,240,240)",
        "theme": "light"
    }
}
```

#### task.json for PnP Xml Task
```
{
    "name": "PnPDeploySpArtifacts",
    "friendlyName": "Deploy SharePoint PnP Artifacts",
    "description": "Deploys SharePoint artifacts with the PnP provisioning engine.",
    "author": "Sebastian Schütze",
    "helpMarkDown": "It uses the Apply-PnPProvisioningTemplate command from the PnP PowerShell Module.<br/><br/>[More Information](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/apply-pnpprovisioningtemplate?view=sharepoint-ps)",
    "demands": ["PowerShell"],
    "instanceNameFormat": "Deploy SharePoint Artifacts for $(SharePointVersion)"   
}
```

These are the current information. So let's discuss which information make sense and which not.

**Comment by SebastianSchuetze** [comment]
@estruyf somehow I can't mention Vincent. Can you please? 

... btw. do you know why I can't?

**Comment by SebastianSchuetze** [comment]
@baywet and @estruyf  could you give some opinion in the most important point like logo and naming? Those are the most important points

**Comment by baywet** [comment]
For the logo why don't we simply the PnP Logo?

**Comment by SebastianSchuetze** [comment]
Do you have a good resolution of the PnP Logo?

**Comment by baywet** [comment]
Not myself, we should ping Vesa internally on that request, go ahead and send him a Dear Vesa email ;-)

**Comment by baywet** [comment]
@SebastianSchuetze from the ongoing pnp call https://github.com/pnp/media :)
